cache:
    key: '${CI_COMMIT_SHORT_SHA}'
    paths:
        - vendor/

variables:
    CONFIG_DIR: /var/configs/$CI_PROJECT_NAME
    STG_CONFIG_DIR: '/var/configs/sts-bistro-api/stg'
    PROD_CONFIG_DIR: '/var/configs/sts-bistro-api/prod'

stages:
    - build
    - lint
    - test
    - push_registry
    - deploy_config
    - deploy

build:
    stage: build
    except:
        - tags
    script:
        - 'docker build -t sts-bistro-api-build-app -f docker/php-fpm/Dockerfile .'
        - 'docker build -t sts-bistro-api-php-fpm -f docker/php-fpm/Dockerfile.test .'

lint:
    except:
        - tags
    script:
        - 'docker run -w /application/app sts-bistro-api-php-fpm vendor/bin/php-cs-fixer --config=.php-cs-fixer.dist.php fix -v --dry-run --stop-on-violation'

test:
    stage: test
    except:
        - tags
    script:
        - 'docker run -w /application/app sts-bistro-api-php-fpm php bin/phpunit --coverage-text --colors=never'
    coverage: '/^\s*Lines:\s*\d+.\d+\%/'

analyse:
    stage: test
    except:
        - tags
    allow_failure: true
    script:
        - 'docker run -w /application/app sts-bistro-api-php-fpm vendor/bin/phpstan analyse -c phpstan.neon --memory-limit 512M'

push_registry:
    stage: push_registry
    only:
        refs:
            - main
    except:
        - tags
    script:
        - 'docker build -t sts-bistro-api-php-fpm -f docker/php-fpm/Dockerfile.prod .'
        - 'docker tag sts-bistro-api-php-fpm gcr.io/tech-stuff-304507/sts-bistro-api-php-fpm:v${CI_COMMIT_SHA:0:8}'
        - 'docker push gcr.io/tech-stuff-304507/sts-bistro-api-php-fpm:v${CI_COMMIT_SHA:0:8}'

deploy_config_stg:
    stage: deploy_config
    only:
        refs:
            - main
    script:
        - 'gcloud container clusters get-credentials staging-apps-a --zone europe-west4-a --project tech-stuff-304507'
        - 'kubectl apply -f $STG_CONFIG_DIR/config-map.k8s.yml'

deploy_stg:
    stage: deploy
    only:
        refs:
            - main
    before_script:
        - 'gcloud container clusters get-credentials staging-apps-a --zone europe-west4-a --project tech-stuff-304507'
    script:
        - 'sed -i "s/<VERSION>/${CI_COMMIT_SHA:0:8}/g" sts-bistro-api.k8s.yml'
        - 'kubectl apply -f sts-bistro-api.k8s.yml'
        - 'kubectl apply -f sts-bistro-api-ingress-staging.k8s.yml'

deploy_config_prod:
    stage: deploy_config
    only:
        - tags
    script:
        - 'gcloud container clusters get-credentials production-apps-b --region europe-central2 --project tech-stuff-304507'
        - 'kubectl apply -f $PROD_CONFIG_DIR/config-map.k8s.yml'

deploy_prod:
    stage: deploy
    only:
        - tags
    before_script:
        - 'gcloud container clusters get-credentials production-apps-b --region europe-central2 --project tech-stuff-304507'
    script:
        - 'sed -i "s/<VERSION>/${CI_COMMIT_SHA:0:8}/g" sts-bistro-api.k8s.yml'
        - 'kubectl apply -f sts-bistro-api.k8s.yml'
        - 'kubectl apply -f sts-bistro-api-ingress-staging.k8s.yml'
